Upgrade asciidoctor and dependencies to latest versions
asciidoctor/docker-asciidoctor pull request #165
Opened 2020-11-20 18:51 UTC by sapientpants

2020-12-10 17:29 UTC, dduportal commented
Thanks for your contribution and your patience! I took the freedom to fix conflicts on your PR so it's up to date with latest changes.

Closes #167

2020-12-10 17:34 UTC, dduportal requested changes
Hello @sapientpants , thanks a lot for your contribution and patience!

This PR is ready to be merged except for the `FROM` diretctive change.

Would you mind fixing it please?

2020-12-10 17:34 UTC, dduportal commented on Dockerfile
> +FROM alpine:3.12.1
Is there a particular reason for this change?
For information, the Docker Image is rebuilt automatically when the upstream `alpine:3.12` image is updated,
so this change is not needed:

<img width="1232" alt="Screenshot 2020-12-10 at 18 31 14" src="https://user-images.githubusercontent.com/1522731/101808001-130efa00-3b16-11eb-87a0-92bd6c0bd72e.png">

2020-12-10 17:34 UTC, dduportal commented on Dockerfile
> +FROM alpine:3.12.1
```suggestion
FROM alpine:3.12
```

2020-12-12 18:08 UTC, slonopotamus commented on README.adoc
> +* https://github.com/asciidoctor/asciidoctor-bibtex[Asciidoctor Bibtex] 0.80.0
This should be `0.8.0`, not `0.80.0`

2020-12-12 18:09 UTC, slonopotamus commented on README.md
> +-   [Asciidoctor Bibtex](https://github.com/asciidoctor/asciidoctor-bibtex) 0.80.0
Same problem as in README.adoc.

2020-12-13 15:33 UTC, jirutka commented on Dockerfile
> +    bigdecimal \
If bigdecimal is needed, install the version shipped with ruby, it's provided by Alpine package ruby-bigdecimal.

2021-01-05 10:05 UTC, sapientpants commented
The outstanding change requests should all be taken care of with the latest commit.

2021-01-05 13:41 UTC, dduportal approved these changes
LGTM, thanks for this contribution ! 👍

2021-01-05 13:42 UTC, merged